version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  register-server:
    build:
      context: ./RegisterService
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - microservices-network

  gateway-service:
    build:
      context: ./ApiGateway
    ports:
      - "9091:9091"
    depends_on:
      - mysql
      - register-server
    networks:
      - microservices-network

  client-service:
    build:
      context: ./ClientService
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - register-server
      - gateway-service
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  voiture-service:
    build:
      context: ./VoitureService
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - register-server
      - gateway-service
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/voituredb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge