server:
  port: 9091

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka : true
    service-url:
      defaultZone: ${EUREKA_SERVER-ADDRESS:http://register-server:8761/eureka}
spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      enabled: true






# eureka.instance.hostname=localhost
# eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
# logging.level.root=INFO
# logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
# logging.level.org.springframework.cloud.gateway=TRACE