# # server:
# #   port: 8084
# # spring:
# #   cloud:
# #     discovery:
# #       enabled: true
# #   datasource:
# #     url: jdbc:mysql://localhost:3306/voituredb?createDatabaseIfNotExist=true
# #     username: root
# #     password: root
# #     driver-class-name: com.mysql.cj.jdbc.Driver
# #   application:
# #     name: VOITURE-SERVICES
# #   jpa:
# #     hibernate:
# #       ddl-auto: update
# #     show-sql: true

# # eureka:
# #   instance:
# #     prefer-ip-address: true
# #   client:
# #     fetch-registry: true
# #     register-with-eureka : true
# #     service-url:
# #       defaultZone: ${EUREKA_SERVER-ADDRESS:http://register-server:8761/eureka}
# server:
#   port: 8084

# spring:
#   cloud:
#     discovery:
#       enabled: true
#       service-name: voiture-services
#   datasource:
#     url: jdbc:mysql://localhost:3306/voituredb?createDatabaseIfNotExist=true
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   application:
#     name: voiture-services
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# # Consul Configuration
# spring.cloud.consul:
#   host: localhost
#   port: 8500
#   discovery:
#     service-name: voiture-services
#     register: true
#     health-check-path: /actuator/health
spring:
  cloud:
    discovery:
      enabled: true
    consul:
      host: localhost
      port: 8500
      discovery: VOITURE-SERVICES
  application:
    name: VOITURE-SERVICES
  datasource:
    url: jdbc:mysql://localhost:3306/Micro_ClientDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8099

